// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vweeeztibtseomcgvqnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3ZWVlenRpYnRzZW9tY2d2cW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODA1MjEsImV4cCI6MjA2MTE1NjUyMX0.6DaAgAyUNbJb0qtPF57uGwZ62V5aG5wsdk1-w-7rciY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);